### ISSUE TITLE
Videos don't play on iOS

### ISSUE THREAD

**Issue by scalerow** [alangrainger/immich-public-proxy#25]
### Setup
**Immich-compose:**
```
  immich-server:
    container_name: immich_server
    profiles:
      - immich
      - all
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - $DATADIR/media/personal_photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/media/external_photos:/usr/src/app/external
    extends:
      # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: $DOCKERDIR/scripts/immich/hwaccel.transcoding.yml
      service: nvenc
    ports:
      - 2283:2283
    depends_on:
      - immich-redis
      - immich-database
    environment:
      PUID: $PUID
      PGID: $PGID
      DB_HOSTNAME: immich_postgres
      DB_USERNAME: $DEFAULT_SIMPLE_USERNAME
      DB_DATABASE_NAME: immich
      DB_PASSWORD: $DEFAULT_PASSWORD
      REDIS_HOSTNAME: immich_redis
      EXTERNAL_PATH: /mnt/data/media/external_photos
    restart: always
    networks:
      - immich_internal
      - traefik_proxy
    labels:
      traefik.enable: true
      traefik.http.services.immich-svc.loadbalancer.server.port: 2283
      traefik.http.routers.immich-rtr.entryPoints: https
      traefik.http.routers.immich-rtr.rule: Host(`my.example.com`)
      traefik.http.routers.immich-rtr.service: immich-svc
      traefik.http.routers.immich-rtr.middlewares: default-noauth-media@file
      traefik.http.routers.immich-rtr.tls.options: mtlsfamily@file
```
Note: I have also enabled a storage template like this; "{{y}}/{{MM}}/{{filename}}" , and enabled transcoding of files to x264/1080

**Immich-public-proxy compose**
```
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: always
    ports:
      - 3007:3000
    environment:
      IMMICH_URL: http://172.21.0.2:2283
      PROXY_PUBLIC_URL: https://my.example.com
      PORT: 3000
      CACHE_AGE: 2592000
    networks:
      - immich_internal
      - traefik_proxy
    labels:
      traefik.enable: true
      traefik.http.routers.photos.entryPoints: https
      traefik.http.routers.photos.rule: Host(`my-external.example.com`)
      traefik.http.routers.photos.middlewares: default-noauth@file
      traefik.http.services.photos.loadbalancer.server.port: 3000
```

****
Config file:

```
{
  "ipp": {
    "responseHeaders": {
      "Cache-Control": "public, max-age=2592000",
      "Access-Control-Allow-Origin":  "*"
    },
    "singleImageGallery": false,
    "singleItemAutoOpen": false,
    "downloadOriginalPhoto": true,
    "showGalleryTitle": true,
    "allowDownloadAll": true
  },
  "lightGallery": {
    "controls": true,
    "download": true,
    "mobileSettings": {
      "controls": true,
      "showCloseIcon": true,
      "download": true
    }
  }
}
```

**iOS:**
1. Share a few pictures/videos from upload lib, using default options
2. Open link in Safari iOS 18 
3. Click play on video 
4. Nothing happens, video playback says 0:00/0:00 and its black
5. Try download button, nothing happens

**Windows/Mac**
1. Share a few pictures/videos from upload lib, using default options
2. Open link in browser (Firefox/Safari/Chrome)
3. Click play on video
4. Video playback is working 
5. Click download - Nothing happnes
6. Click download all - downloads a file matching in size, but is corrupted and cant be unpacked
