### ISSUE TITLE
Help understanding

### ISSUE THREAD

**Issue by DdHms** [alangrainger/immich-public-proxy#56]
Hi your project seems really great though I am not quite sure how to make it work

my server is within a vpn network and port 2283 is served to a duckdns url using a reverse proxy
I also have port 80 served outside the internet using Tailscale funnel
my reverse proxy is nginx based.
As far as I understand the `IMMICH_URL ` is probably localhost:2283 but how do I connect my tailscale with a specific sub_route to `localhost:2283/share` 
Shouldn't I declare what my `https://your-proxy-url.com` is in the docker-compose file?

**Comment by alangrainger** [comment]
If you're using docker for Immich, the IP won't be `localhost`. It needs to be the IP of your docker server inside your internal network.

`localhost` only applies to the active container.

**Comment by DdHms** [comment]
I must be missing something here:
`564858db33c2   ghcr.io/immich-app/immich-server:release             "tini -- /bin/bash s…"   3 days ago      Up 2 days (healthy)        0.0.0.0:2283->2283/tcp, :::2283->2283/tcp   immich_server
`
This is my docker container
I tried using several ip addresses but keep getting `Unable to reach Immich on ###`
Do you have a command that could help me determine the correct ip address

**Comment by alangrainger** [comment]
Closing as this isn't an issue, we can continue talking though.

**Comment by alangrainger** [comment]
What is the IP address of the server running Immich? Is that IP address accessible to the server running IPP? Or maybe it is the same server.

Use that IP address and whatever port Immich is exposed on.

**Comment by DdHms** [comment]
Both docker containers live on the same machine

**Comment by alangrainger** [comment]
And what happened when you "Use that IP address and whatever port Immich is exposed on." ?

**Comment by DdHms** [comment]
I keep getting a print in the IPP logs of "Unable to reach immich on ..."
I looked at the logs in the immich service and it displays:
` Immich Server is listening on http://[::1]:2283 [v1.125.7] [production] 
`
but 
Unable to reach Immich on http://[::1]:2283
I haven't done any changes to the immich dockerfile other than volume mapping and as said above both immich and IPP are running on the same machine as different docker containers

**Comment by alangrainger** [comment]
What is the IP address of the server running Immich and IPP?

**Comment by DdHms** [comment]
ifconfig output:

<img width="489" alt="Image" src="https://github.com/user-attachments/assets/59619151-0e56-4012-8d87-db37f9ac528c" />

<img width="496" alt="Image" src="https://github.com/user-attachments/assets/01a05430-568a-4711-8ca3-c08af04bb04c" />

<img width="454" alt="Image" src="https://github.com/user-attachments/assets/d24b9e8f-1d01-4f9b-8b89-1796d8d41809" />
Quite a few as you see..

**Comment by alangrainger** [comment]
I wouldn't know - it's your server. But whatever address you would use to reach Immich via a local network - use that one.

**Comment by DdHms** [comment]
OK I got it to work and I think it is worth adding to your docs.
1. immich services all communicate over a docker network named `immich_default` so one can update your docker image as follows:
```

services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: always
    ports:
      - "3000:3000"
    environment:
      - IMMICH_URL=http://immich_server:2283
    networks:
      - immich_default
    healthcheck:
     test: wget -q --spider http://localhost:3000/share/healthcheck || exit 1
     start_period: 10s
     timeout: 5s

networks:
  immich_default:
    external: true
```
I can also add from my experience with NginX reverse proxy (not just caddy):
```
server {
listen 80;
server_name  <Your Serving URL>;

        location /share {
        return 301 /share/;
    }

    location /share/ {
        proxy_pass http://localhost:3000/share/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

}
```
