### ISSUE TITLE
Config doesn't seem to load

### ISSUE THREAD

**Issue by hunterwinterton** [alangrainger/immich-public-proxy#68]
Hi! I am enjoying the look and security of Immich Public Proxy, but I haven't been able to change anything in the config. I have tried to make it show the title and allow download for all images, but the changes aren't happening when I open a gallery. There are no errors in the logs. I'm not sure if I'm doing something wrong or if its a bug. Any help is appreciated.

Here is my docker compose:
```yaml
 immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    #user: 3002:999
    restart: always
    ports:
      - 3010:3000
    environment:
      - IMMICH_URL=http://immich-server:2283
    volumes:
      - /mnt/data/immich-public-proxy/config.json:/app/config.json
    healthcheck:
      test: wget -q --spider http://localhost:3000/share/healthcheck || exit 1
      start_period: 10s
      timeout: 5s
```

Here is my config:
```json
{
  "ipp": {
    "responseHeaders": {
      "Cache-Control": "public, max-age=2592000",
      "Access-Control-Allow-Origin":  "*"
    },
    "singleImageGallery": false,
    "singleItemAutoOpen": true,
    "downloadOriginalPhoto": true,
    "showGalleryTitle": true,
    "allowDownloadAll": true,
    "showHomePage": false
  },
  "lightGallery": {
    "controls": true,
    "download": true,
    "mobileSettings": {
      "controls": false,
      "showCloseIcon": true,
      "download": true
    }
  }
}
```

**Comment by alangrainger** [comment]
If you log into the container shell, can you cat the file and see the correct contents?

This isn't an issue with IPP, this is just standard troubleshooting.

**Comment by hunterwinterton** [comment]
> This is not an IPP issue, so you'll need to do some standard troubleshooting:
> 
> * If you log into the container shell, can you cat the file and see the correct contents?
> * Does the `node` user have permissions to read that file?
> * Are you running a cache in front or in your browser which is showing a cached previous result?

It turns out it was a permissions issue, changing the config file to 644 fixed the issue. Thanks for your help

**Comment by lennartbrandin** [comment]
I have the same issue, i want to enable the download all feature (and disable homepage icon).
Yet the config doesnt seem to have any effect
## Permission
```bash
dce immich-public-proxy ls -lh 
total 236K   
-rw-r--r--    1 node     node         593 May  6 06:50 config.json
...
```
## Config.json
```json
{
  "ipp": {
    "responseHeaders": {
      "Cache-Control": "public, max-age=2592000",
      "Access-Control-Allow-Origin":  "*"
    },
    "singleImageGallery": false,
    "singleItemAutoOpen": true,
    "downloadOriginalPhoto": true,
    "allowDownloadAll": 2,
    "showHomePage": false,
    "showGalleryTitle": false,
    "showMetadata": {
      "description": false
    },
    "customInvalidResponse": false
  },
  "lightGallery": {
    "controls": true,
    "download": true,
    "mobileSettings": {
      "controls": false,
      "showCloseIcon": true,
      "download": true
    }
  }
```
AFAIK i tried reloading without caching (after restarting the container multiple times) and using a different browser
## Compose.yaml (canonical)
```yaml
  immich-public-proxy:
    environment:
      IMMICH_CONFIG_FILE: /config.json # Carried over by some shared env file
      IMMICH_URL: http://immich_server:2283
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/Berlin
      UPLOAD_LOCATION: ./library
    healthcheck:
      test:
        - CMD-SHELL
        - curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      timeout: 5s
      start_period: 10s
    image: alangrainger/immich-public-proxy:latest
    labels:
      caddy_1: https://myurl.com
      caddy_1.@pub-photos.path: /*
      caddy_1.reverse_proxy: '@pub-photos {{upstreams 3000}}'
    networks:
      caddy: null
      internal: null
    restart: always
    volumes:
      - type: bind
        source: /h/photos/config-proxy.json
        target: /app/config.json
        read_only: true
        bind:
          create_host_path: true
```
