### ISSUE TITLE
Unable to reach Immich on http://localhost:2283

### ISSUE THREAD

**Issue by hupfdule** [alangrainger/immich-public-proxy#95]
I have just installed immich-public-proxy for the first time. 
This is the docker-compose.yml I am using (I have only changed the IMMICH_URL):

```yml
services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:1.11.1
    container_name: immich-public-proxy
    restart: always
    ports: 
      - "3000:3000"
    environment:
      - IMMICH_URL=http://localhost:2283
    healthcheck:
      test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s
```

I can actually reach it via `http://myserver:3000/` and see the shield logo. But in the logs I get the following error over and over again:

```
Unable to reach Immich on http://localhost:2283
From the server IPP is running on, see if you can curl to http://localhost:2283/api/server/ping and receive a JSON result.
```

If a execute `curl  http://localhost:2283/api/server/ping` on the server I actually get:

```
{"res":"pong"}
```

I don’t really understand what is the problem here. Can you help me here?

**Comment by alangrainger** [comment]
This is a standard Docker "issue", nothing to do with IPP.

`localhost` refers to the IPP container. You need to use your server's IP address.

**Comment by johenning** [comment]
Alternatively, e.g. with Portainer in its standard configuration, every stack has its own subnetwork. Instead of trying to setup routing between them, it might be easiest to just add IPP to the immich stack (if immich was setup with docker compose).
E.g.
```yaml
services:
  immich-server:
    ...
  immich-machine-learning:
    ...
  redis:
    ...
  database:
    ...
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: always
    ports:
      - "3000:3000"
    environment:
      - IMMICH_URL=http://immich_server:2283
    healthcheck:
      test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s

volumes:
  ...
```

`http://immich_server:2283` is resolvable because [docker compose sets up DNS records to resolve all service names](https://docs.docker.com/compose/how-tos/networking/)
